repos:
  # Python formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-executables-have-shebangs

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^src/api/.*\.py$

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--multi-line", "3"]
        files: ^src/api/.*\.py$

  # Python flake8 linting
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
        files: ^src/api/.*\.py$

  # JavaScript/Vue formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^src/ui/.*\.(js|vue|json|css|html)$
        exclude: ^src/ui/(node_modules|dist|build)/.*$

  # Vue.js specific linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: ^src/ui/.*\.(js|vue)$
        exclude: ^src/ui/(node_modules|dist|build)/.*$
        args: [--fix]
        additional_dependencies:
          - eslint@^8.57.0
          - "@vue/eslint-config-prettier"
          - "eslint-plugin-vue"

  # Django specific checks
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.23.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"]
        files: ^src/api/.*\.py$

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: ["-r", "src/api", "-x", "*/tests/*,*/migrations/*"]
        files: ^src/api/.*\.py$

  # MyPy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^src/api/.*\.py$
        exclude: ^src/api/.*(migrations|tests)/.*\.py$
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
          - types-PyYAML
          - types-Pillow