version: '3.8'

services:
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app
      - api_data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=mosaic_api.settings
      - DEBUG=1
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_exact &&
             python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/aircraft/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/ui:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  api_data: