version: '3.8'

services:
  api:
    build:
      context: src/api
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - ./src/api:/app
      - api_data:/app/data
    environment:
      - DJANGO_SETTINGS_MODULE=mosaicplane.settings
      - DEBUG=True
      - DOCKER_COMPOSE=true
    command: >
      sh -c "python manage.py migrate &&
             python manage.py initialize_feature_flags --reset &&
             python manage.py seed &&
             python manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/v1/aircraft/', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ui:
    build:
      context: ./src/ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/ui:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - ui
    restart: unless-stopped

volumes:
  api_data:
