name = "mosaicplane-info-ui"
compatibility_date = "2024-12-12"
preview_urls = true

# Static assets configuration
[assets]
directory = "./dist"
not_found_handling = "single-page-application"

# Environment variables
[vars]
ENVIRONMENT = "development"
API_BASE_URL = "http://localhost:8000"

# Custom domains (configure these after deployment)
# routes = [
#   { pattern = "mosaicplane.info/*", zone_name = "mosaicplane.info" }
# ]

# Development settings
[env.development]
name = "mosaicplane-info-ui-dev"

[env.development.vars]
ENVIRONMENT = "development"
API_BASE_URL = "http://localhost:8000"

# Production settings
[env.production]
name = "mosaicplane-info-ui-prod"

[env.production.vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://api.mosaicplane.info"